FROM rust 

WORKDIR /usr/src/akm_rust


COPY . .
RUN cargo install diesel_cli --no-default-features --features postgres
RUN cargo install cargo-watch

# RUN ./diesel_migrations.sh

CMD [ "cargo","watch","-x","run" ]

# docker run --rm -p 8000:8000 -v .:/usr/src/akm_rust akm-rus